<?php

namespace App\Http\Controllers;

use Illuminate\Http\Request;
use App\Models\Member;
use App\Models\Contribution;
use App\Models\User;
use Illuminate\Support\Facades\Hash;
use Illuminate\Support\Facades\Response;


class MemberController extends Controller
{
    /**
     * Member dashboard - shows logged-in member's own details.
     */
    public function myDashboard()
    {
        $user = auth()->user();
        
        // Check if user has a linked member profile
        if (!$user->member_id) {
            return redirect()->route('members.pending-approval')
                ->with('error', 'Your account is not linked to a member profile. Please contact the administrator.');
        }
        
        $member = Member::findOrFail($user->member_id);
        
        // Get contributions for payment calendar
        $contributions = Contribution::where('member_id', $member->id)
            ->orderBy('contribution_date', 'asc')
            ->get();

        // Calculate outstanding balance
        $startDate = $member->getJoinDate();
        $endOfLastMonth = \Carbon\Carbon::now()->subMonth()->endOfMonth();
        if ($endOfLastMonth < $startDate) {
            $endOfLastMonth = $startDate->copy()->subDay();
        }
        
        $previousExpected = 0;
        $currentDate = clone $startDate;
        while ($currentDate <= $endOfLastMonth) {
            $year = $currentDate->year;
            $expectedMonthly = ($year >= 2026) ? 300 : 250;
            $previousExpected += $expectedMonthly;
            $currentDate->addMonth();
        }
        
        $previousPaid = $member->contributions()
            ->where('type', 'monthly_contribution')
            ->where('contribution_date', '>=', $startDate)
            ->where('contribution_date', '<=', $endOfLastMonth)
            ->sum('amount');
        
        $previousOutstanding = max(0, $previousExpected - $previousPaid);
        
        $currentMonth = \Carbon\Carbon::now()->startOfMonth();
        $currentMonthExpected = 0;
        if ($currentMonth >= $startDate) {
            $year = $currentMonth->year;
            $currentMonthExpected = ($year >= 2026) ? 300 : 250;
        }
        
        $currentMonthPaid = $member->contributions()
            ->where('type', 'monthly_contribution')
            ->where('contribution_date', '>=', $currentMonth)
            ->where('contribution_date', '<=', \Carbon\Carbon::now()->endOfMonth())
            ->sum('amount');
        
        $currentMonthOutstanding = max(0, $currentMonthExpected - $currentMonthPaid);
        $outstanding = $previousOutstanding + $currentMonthOutstanding;
        $expectedTotal = $previousExpected + $currentMonthExpected;
        $totalPaid = $previousPaid + $currentMonthPaid;
        
        // Get registration status
        $registrationFeePaid = $member->contributions()
            ->where('type', 'registration_fee')
            ->sum('amount');
        $isRegistered = $registrationFeePaid >= 1000;

        // Get pending payment requests
        $pendingPayments = \App\Models\PaymentRequest::where('member_id', $member->id)
            ->where('status', 'pending')
            ->orderByDesc('created_at')
            ->get();

        // Get QPL games for this member
        $qplGames = \App\Models\QplGame::where(function($query) use ($member) {
                $query->where('home_team', $member->name)
                      ->orWhere('away_team', $member->name);
            })
            ->orderBy('game_date', 'desc')
            ->orderBy('created_at', 'desc')
            ->get();

        // Get upcoming calendar activities
        $upcomingActivities = \App\Models\CalendarActivity::where('activity_date', '>=', now()->startOfDay())
            ->whereIn('status', ['scheduled', 'completed'])
            ->orderBy('activity_date', 'asc')
            ->orderBy('start_time', 'asc')
            ->limit(20)
            ->get();

        // Calculate QPL stats
        $qplStats = [
            'played' => 0,
            'won' => 0,
            'drawn' => 0,
            'lost' => 0,
            'goals_for' => 0,
            'goals_against' => 0,
            'points' => 0,
        ];

        foreach ($qplGames as $game) {
            $isAutoGenerated = ($game->notes === 'Auto-generated fixture');
            $hasBeenUpdated = ($game->updated_at != $game->created_at);
            $hasScores = ($game->home_score > 0 || $game->away_score > 0);
            $isPlayed = !$isAutoGenerated || $hasBeenUpdated || $hasScores;
            
            if ($isPlayed) {
                $qplStats['played']++;
                
                if ($game->home_team === $member->name) {
                    $qplStats['goals_for'] += $game->home_score;
                    $qplStats['goals_against'] += $game->away_score;
                    
                    if ($game->home_score > $game->away_score) {
                        $qplStats['won']++;
                        $qplStats['points']++;
                    } elseif ($game->home_score < $game->away_score) {
                        $qplStats['lost']++;
                    } else {
                        $qplStats['drawn']++;
                    }
                } else {
                    $qplStats['goals_for'] += $game->away_score;
                    $qplStats['goals_against'] += $game->home_score;
                    
                    if ($game->away_score > $game->home_score) {
                        $qplStats['won']++;
                        $qplStats['points']++;
                    } elseif ($game->away_score < $game->home_score) {
                        $qplStats['lost']++;
                    } else {
                        $qplStats['drawn']++;
                    }
                }
            }
        }

        return view('members.my-dashboard', compact(
            'member',
            'contributions',
            'totalPaid',
            'outstanding',
            'expectedTotal',
            'isRegistered',
            'registrationFeePaid',
            'pendingPayments',
            'qplGames',
            'qplStats',
            'upcomingActivities'
        ));
    }

    /**
     * Display a listing of the members.
     */
    public function index(Request $request)
    {
        $query = Member::with('contributions');
        
        // Search functionality
        if ($request->has('search') && $request->search) {
            $search = $request->search;
            $query->where(function($q) use ($search) {
                $q->where('name', 'like', "%{$search}%")
                  ->orWhere('member_no', 'like', "%{$search}%")
                  ->orWhere('phone', 'like', "%{$search}%")
                  ->orWhere('initials', 'like', "%{$search}%");
            });
        }
        
        $members = $query->orderBy('name')->get();
        
        // Add registration status for each member
        $members->each(function($member) {
            $registrationFeePaid = $member->contributions()
                ->where('type', 'registration_fee')
                ->sum('amount');
            $member->isRegistered = $registrationFeePaid >= 1000;
            $member->registrationFeePaid = $registrationFeePaid;
        });
        
        return view('members.index', compact('members'));
    }

    /**
     * Display the specified member with tabs.
     */
    public function show(Member $member)
    {
        // Get contributions for payment calendar
        $contributions = Contribution::where('member_id', $member->id)
            ->orderBy('contribution_date', 'asc')
            ->get();

        // Calculate outstanding balance: previous balance + current month only (not whole year)
        $startDate = $member->getJoinDate(); // First contribution = joining date
        
        // Previous outstanding (from join date to end of last month)
        $endOfLastMonth = \Carbon\Carbon::now()->subMonth()->endOfMonth();
        if ($endOfLastMonth < $startDate) {
            $endOfLastMonth = $startDate->copy()->subDay();
        }
        
        $previousExpected = 0;
        $currentDate = clone $startDate;
        while ($currentDate <= $endOfLastMonth) {
            $year = $currentDate->year;
            $expectedMonthly = ($year >= 2026) ? 300 : 250;
            $previousExpected += $expectedMonthly;
            $currentDate->addMonth();
        }
        
        $previousPaid = $member->contributions()
            ->where('type', 'monthly_contribution')
            ->where('contribution_date', '>=', $startDate)
            ->where('contribution_date', '<=', $endOfLastMonth)
            ->sum('amount');
        
        $previousOutstanding = max(0, $previousExpected - $previousPaid);
        
        // Current month's outstanding (only current month)
        $currentMonth = \Carbon\Carbon::now()->startOfMonth();
        $currentMonthExpected = 0;
        if ($currentMonth >= $startDate) {
            $year = $currentMonth->year;
            $currentMonthExpected = ($year >= 2026) ? 300 : 250;
        }
        
        $currentMonthPaid = $member->contributions()
            ->where('type', 'monthly_contribution')
            ->where('contribution_date', '>=', $currentMonth)
            ->where('contribution_date', '<=', \Carbon\Carbon::now()->endOfMonth())
            ->sum('amount');
        
        $currentMonthOutstanding = max(0, $currentMonthExpected - $currentMonthPaid);
        
        // Total outstanding = previous + current month
        $outstanding = $previousOutstanding + $currentMonthOutstanding;
        $expectedTotal = $previousExpected + $currentMonthExpected;
        $totalPaid = $previousPaid + $currentMonthPaid;
        
        // Get registration status
        $registrationFeePaid = $member->contributions()
            ->where('type', 'registration_fee')
            ->sum('amount');
        $isRegistered = $registrationFeePaid >= 1000;

        // Get pending payment requests
        $pendingPayments = \App\Models\PaymentRequest::where('member_id', $member->id)
            ->where('status', 'pending')
            ->orderByDesc('created_at')
            ->get();

        // Get QPL games
        $qplGames = \App\Models\QplGame::orderBy('game_date', 'desc')
            ->orderBy('created_at', 'desc')
            ->get();

        // Get upcoming calendar activities (from today onwards, scheduled or completed)
        $upcomingActivities = \App\Models\CalendarActivity::where('activity_date', '>=', now()->startOfDay())
            ->whereIn('status', ['scheduled', 'completed'])
            ->orderBy('activity_date', 'asc')
            ->orderBy('start_time', 'asc')
            ->limit(20) // Show next 20 upcoming activities
            ->get();

        // Calculate which specific months are outstanding
        $outstandingMonths = [];
        $currentDate = clone $startDate;
        $asOfDate = \Carbon\Carbon::now()->endOfMonth();
        
        // Get all monthly contributions grouped by month
        $monthlyContributions = $member->contributions()
            ->where('type', 'monthly_contribution')
            ->get()
            ->groupBy(function($contribution) {
                return $contribution->contribution_date->format('Y-m');
            })
            ->map(function($contributions) {
                return $contributions->sum('amount');
            });
        
        while ($currentDate <= $asOfDate) {
            $year = $currentDate->year;
            $month = $currentDate->month;
            
            // Skip Jan-June 2024 (club started in July)
            if ($year == 2024 && $month < 7) {
                $currentDate->addMonth();
                continue;
            }
            
            $monthKey = $currentDate->format('Y-m');
            $expectedAmount = ($year >= 2026) ? 300 : 250;
            $paidAmount = $monthlyContributions->get($monthKey, 0);
            
            if ($paidAmount < $expectedAmount) {
                $outstandingMonths[] = [
                    'year' => $year,
                    'month' => $month,
                    'month_name' => $currentDate->format('F Y'),
                    'short_month' => $currentDate->format('M Y'),
                    'expected' => $expectedAmount,
                    'paid' => $paidAmount,
                    'outstanding' => $expectedAmount - $paidAmount,
                ];
            }
            
            $currentDate->addMonth();
        }

        return view('members.show', compact(
            'member',
            'contributions',
            'totalPaid',
            'outstanding',
            'isRegistered',
            'registrationFeePaid',
            'pendingPayments',
            'qplGames',
            'upcomingActivities',
            'outstandingMonths'
        ));
    }

    /**
 * Display member contribution statement
 */
public function statement(Member $member)
{
    $contributions = Contribution::where('member_id', $member->id)
        ->orderBy('contribution_date', 'asc')
        ->get();

    $total = $contributions->sum('amount');
    
    // Calculate outstanding balance: previous balance + current month only (not whole year)
    $startDate = $member->getJoinDate(); // First contribution = joining date
    
    // Previous outstanding (from join date to end of last month)
    $endOfLastMonth = \Carbon\Carbon::now()->subMonth()->endOfMonth();
    if ($endOfLastMonth < $startDate) {
        $endOfLastMonth = $startDate->copy()->subDay();
    }
    
    $previousExpected = 0;
    $currentDate = clone $startDate;
    while ($currentDate <= $endOfLastMonth) {
        $year = $currentDate->year;
        $expectedMonthly = ($year >= 2026) ? 300 : 250;
        $previousExpected += $expectedMonthly;
        $currentDate->addMonth();
    }
    
    $previousPaid = $member->contributions()
        ->where('type', 'monthly_contribution')
        ->where('contribution_date', '>=', $startDate)
        ->where('contribution_date', '<=', $endOfLastMonth)
        ->sum('amount');
    
    $previousOutstanding = max(0, $previousExpected - $previousPaid);
    
    // Current month's outstanding (only current month)
    $currentMonth = \Carbon\Carbon::now()->startOfMonth();
    $currentMonthExpected = 0;
    if ($currentMonth >= $startDate) {
        $year = $currentMonth->year;
        $currentMonthExpected = ($year >= 2026) ? 300 : 250;
    }
    
    $currentMonthPaid = $member->contributions()
        ->where('type', 'monthly_contribution')
        ->where('contribution_date', '>=', $currentMonth)
        ->where('contribution_date', '<=', \Carbon\Carbon::now()->endOfMonth())
        ->sum('amount');
    
    $currentMonthOutstanding = max(0, $currentMonthExpected - $currentMonthPaid);
    
    // Total outstanding = previous + current month
    $outstanding = $previousOutstanding + $currentMonthOutstanding;
    $expectedTotal = $previousExpected + $currentMonthExpected;
    $totalPaid = $previousPaid + $currentMonthPaid;
    
    // Calculate months behind
    $months = $startDate->diffInMonths(\Carbon\Carbon::now()->endOfMonth()) + 1;
    $avgExpectedMonthly = $months > 0 ? $expectedTotal / $months : 250;
    $monthsBehind = $avgExpectedMonthly > 0 ? ceil($outstanding / $avgExpectedMonthly) : 0;
    
    // Check if member has paid registration fee (1000)
    $registrationFeePaid = $member->contributions()
        ->where('type', 'registration_fee')
        ->sum('amount');
    $isRegistered = $registrationFeePaid >= 1000;

    return view('members.statement', compact(
        'member',
        'contributions',
        'total',
        'expectedTotal',
        'totalPaid',
        'outstanding',
        'monthsBehind',
        'registrationFeePaid',
        'isRegistered'
    ));
}


    /**
     * Show the form for creating a new member.
     */
    public function create()
    {
        return view('members.create');
    }

    /**
     * Store a newly created member in storage.
     */
    public function store(Request $request)
    {
        // Validate the request according to the migration structure
        $validated = $request->validate([
            'member_no' => 'required|unique:members,member_no|max:50',
            'name' => 'required|string|max:150',
            'initials' => 'required|string|max:50',
            'registration_amount_paid' => 'required|string|max:191',
            'registration_fee' => 'nullable|numeric|min:0',
            'paid_to_date' => 'required|string|max:191',
            'phone' => 'nullable|string|max:50',
            'status' => 'nullable|string|in:ACTIVE,INACTIVE',
        ]);

        // Set default registration_fee if not provided
        if (!isset($validated['registration_fee']) || empty($validated['registration_fee'])) {
            $validated['registration_fee'] = 1000;
        }

        // Create the member
        $member = Member::create(array_merge($validated, [
            'status' => $validated['status'] ?? 'ACTIVE',
        ]));

        // Create user account for member if phone is provided
        if ($member->phone) {
            // Check if user already exists with this phone
            $existingUser = User::where('phone', $member->phone)->first();
            
            if (!$existingUser) {
                // Create user account for member
                User::create([
                    'name' => $member->name,
                    'initials' => $member->initials,
                    'email' => $member->member_no . '@member.local',
                    'phone' => $member->phone,
                    'password' => Hash::make('eldoret2010'),
                    'role' => 'member',
                    'member_id' => $member->id,
                ]);
            }
        }

        // Redirect back to index with success message
        return redirect()->route('members.index')
                         ->with('success', 'Member created successfully! User account created with password: eldoret2010');
    }

    /**
     * Show the form for editing an existing member.
     */
    public function edit(Member $member)
    {
        return view('members.edit', compact('member'));
    }

    /**
     * Update an existing member in storage.
     */
    public function update(Request $request, Member $member)
    {
        $validated = $request->validate([
            'member_no' => "required|unique:members,member_no,{$member->id}|max:50",
            'name' => 'required|string|max:150',
            'initials' => 'required|string|max:50',
            'registration_amount_paid' => 'required|string|max:191',
            'registration_fee' => 'nullable|numeric|min:0',
            'paid_to_date' => 'required|string|max:191',
            'phone' => 'nullable|string|max:50',
            'status' => 'nullable|string|in:ACTIVE,INACTIVE',
        ]);

        // Set default registration_fee if not provided
        if (!isset($validated['registration_fee']) || empty($validated['registration_fee'])) {
            $validated['registration_fee'] = $member->registration_fee ?? 1000;
        }

        $member->update($validated);

        return redirect()->route('members.index')
                         ->with('success', 'Member updated successfully!');
    }

    /**
     * Remove a member from storage.
     */
    public function destroy(Member $member)
    {
        $member->delete();

        return redirect()->route('members.index')
                         ->with('success', 'Member deleted successfully!');
    }

    /**
     * Show the form for importing members from Excel.
     */
    public function showImportForm()
    {
        return view('members.import');
    }

    /**
     * Import members from Excel/CSV file.
     */
    public function import(Request $request)
    {
        $request->validate([
            'file' => 'required|mimes:csv,txt|max:10240',
        ]);

        try {
            $importedCount = 0;
            $errors = [];
            $file = $request->file('file');
            $extension = $file->getClientOriginalExtension();
            
            // Handle CSV files
            if (strtolower($extension) === 'csv') {
                $handle = fopen($file->getRealPath(), 'r');
                if ($handle === false) {
                    throw new \Exception('Could not open file');
                }
                
                // Read header row
                $headers = fgetcsv($handle);
                if ($headers === false) {
                    fclose($handle);
                    throw new \Exception('File is empty or invalid');
                }
                
                // Remove BOM if present
                if (!empty($headers[0]) && substr($headers[0], 0, 3) === "\xEF\xBB\xBF") {
                    $headers[0] = substr($headers[0], 3);
                }
                
                // Store original headers for error messages
                $originalHeaders = $headers;
                
                // Normalize headers (trim, lowercase, remove spaces and special chars)
                $normalizedHeaders = array_map(function($h) {
                    return strtolower(trim(preg_replace('/[^a-z0-9_]/', '_', $h)));
                }, $headers);
                
                // Find column indices (try multiple variations)
                $memberNoIndex = $this->findColumnIndex($normalizedHeaders, ['member_no', 'memberno', 'member_number', 'membernumber']);
                $nameIndex = $this->findColumnIndex($normalizedHeaders, ['name', 'member_name', 'fullname', 'full_name']);
                $initialsIndex = $this->findColumnIndex($normalizedHeaders, ['initials', 'initial']);
                $regAmountIndex = $this->findColumnIndex($normalizedHeaders, ['registration_amount_paid', 'registrationamountpaid', 'reg_amount', 'regamount']);
                $regFeeIndex = $this->findColumnIndex($normalizedHeaders, ['registration_fee', 'registrationfee', 'reg_fee', 'regfee']);
                $paidToDateIndex = $this->findColumnIndex($normalizedHeaders, ['paid_to_date', 'paidtodate', 'paid', 'paidtill']);
                $phoneIndex = $this->findColumnIndex($normalizedHeaders, ['phone', 'phone_number', 'phonenumber', 'mobile', 'tel']);
                $statusIndex = $this->findColumnIndex($normalizedHeaders, ['status', 'member_status']);
                
                if ($memberNoIndex === false || $nameIndex === false || $initialsIndex === false) {
                    fclose($handle);
                    $missing = [];
                    if ($memberNoIndex === false) $missing[] = 'member_no';
                    if ($nameIndex === false) $missing[] = 'name';
                    if ($initialsIndex === false) $missing[] = 'initials';
                    $foundColumns = implode(', ', array_filter($originalHeaders, function($h) { return !empty(trim($h)); }));
                    throw new \Exception('Required columns missing: ' . implode(', ', $missing) . '. Found columns in file: ' . ($foundColumns ?: 'none'));
                }
                
                $lineNumber = 1;
                while (($row = fgetcsv($handle)) !== false) {
                    $lineNumber++;
                    
                    if (count($row) < count($headers)) {
                        continue; // Skip incomplete rows
                    }
                    
                    try {
                        $memberData = [
                            'member_no' => trim($row[$memberNoIndex] ?? ''),
                            'name' => trim($row[$nameIndex] ?? ''),
                            'initials' => trim($row[$initialsIndex] ?? ''),
                            'registration_amount_paid' => $regAmountIndex !== false ? trim($row[$regAmountIndex] ?? '0') : '0',
                            'registration_fee' => $regFeeIndex !== false ? (trim($row[$regFeeIndex] ?? '') ?: 1000) : 1000,
                            'paid_to_date' => $paidToDateIndex !== false ? trim($row[$paidToDateIndex] ?? '0') : '0',
                            'phone' => $phoneIndex !== false ? trim($row[$phoneIndex] ?? '') : null,
                            'status' => $statusIndex !== false ? (trim($row[$statusIndex] ?? '') ?: 'ACTIVE') : 'ACTIVE',
                        ];
                        
                        // Validate required fields
                        if (empty($memberData['member_no']) || empty($memberData['name']) || empty($memberData['initials'])) {
                            $errors[] = "Line {$lineNumber}: Missing required fields";
                            continue;
                        }
                        
                        // Check if member already exists
                        $existingMember = Member::where('member_no', $memberData['member_no'])->first();
                        if ($existingMember) {
                            $errors[] = "Line {$lineNumber}: Member {$memberData['member_no']} already exists";
                            continue;
                        }
                        
                        // Create member
                        $member = Member::create($memberData);
                        $importedCount++;
                        
                        // Create user account if phone is provided
                        if ($member->phone) {
                            $existingUser = User::where('phone', $member->phone)->first();
                            if (!$existingUser) {
                                User::create([
                                    'name' => $member->name,
                                    'initials' => $member->initials ?? '',
                                    'email' => $member->member_no . '@member.local',
                                    'phone' => $member->phone,
                                    'password' => Hash::make('eldoret2010'),
                                    'role' => 'member',
                                    'member_id' => $member->id,
                                ]);
                            }
                        }
                    } catch (\Exception $e) {
                        $errors[] = "Line {$lineNumber}: " . $e->getMessage();
                    }
                }
                
                fclose($handle);
            } else {
                // For XLSX/XLS files, provide a helpful error message
                throw new \Exception('Excel files (.xlsx, .xls) are not supported. Please save your file as CSV format and try again. You can open your Excel file and use "Save As" to save it as CSV.');
            }

            if (count($errors) > 0) {
                return redirect()->route('members.index')
                    ->with('warning', "Imported {$importedCount} members. Some rows had errors.")
                    ->with('import_errors', $errors);
            }

            return redirect()->route('members.index')
                ->with('success', "Successfully imported {$importedCount} members!");
        } catch (\Exception $e) {
            return redirect()->route('members.import.form')
                ->with('error', 'Error importing file: ' . $e->getMessage());
        }
    }

    /**
     * Helper method to find column index by trying multiple possible names
     */
    private function findColumnIndex($headers, $possibleNames)
    {
        foreach ($possibleNames as $name) {
            $index = array_search(strtolower($name), $headers);
            if ($index !== false) {
                return $index;
            }
        }
        return false;
    }

    /**
     * Download CSV template for member import.
     */
    public function downloadTemplate()
    {
        $filename = 'members_template.csv';
        
        $headers = [
            'Content-Type' => 'text/csv',
            'Content-Disposition' => "attachment; filename=\"{$filename}\"",
        ];

        $callback = function() {
            $file = fopen('php://output', 'w');
            
            // Add BOM for UTF-8 (helps Excel display correctly)
            fprintf($file, chr(0xEF).chr(0xBB).chr(0xBF));
            
            // Header row
            fputcsv($file, [
                'member_no',
                'name',
                'initials',
                'registration_amount_paid',
                'registration_fee',
                'paid_to_date',
                'phone',
                'status'
            ]);
            
            // Example rows
            fputcsv($file, ['M001', 'John Doe', 'JD', '1000', '1000', '1000', '1234567890', 'ACTIVE']);
            fputcsv($file, ['M002', 'Jane Smith', 'JS', '1000', '1000', '1000', '0987654321', 'ACTIVE']);
            
            fclose($file);
        };

        return Response::stream($callback, 200, $headers);
    }
}
