<?php

namespace App\Http\Controllers;

use Illuminate\Http\Request;
use App\Models\QplGame;
use App\Models\Member;

class QplGameController extends Controller
{
    /**
     * Display a listing of QPL games.
     */
    public function index()
    {
        $games = QplGame::orderBy('game_date', 'desc')
            ->orderBy('created_at', 'desc')
            ->get();

        return view('qpl-games.index', compact('games'));
    }

    /**
     * Show form to generate fixtures automatically between members.
     */
    public function generateForm()
    {
        return view('qpl-games.generate');
    }

    /**
     * Generate round-robin fixtures between members starting from a date.
     */
    public function generate(Request $request)
    {
        $data = $request->validate([
            'start_date' => 'required|date',
        ]);

        $startDate = $data['start_date'];

        // Get all members ordered by member number
        $members = Member::orderBy('member_no')->get();

        if ($members->count() < 2) {
            return redirect()->route('qpl-games.index')
                ->with('success', 'Need at least 2 members to generate fixtures.');
        }

        // Simple round-robin: every distinct pair (A vs B)
        $gamesToCreate = [];
        $count = $members->count();

        for ($i = 0; $i < $count; $i++) {
            for ($j = $i + 1; $j < $count; $j++) {
                $memberA = $members[$i];
                $memberB = $members[$j];

                $gamesToCreate[] = [
                    'game_date' => $startDate,
                    'home_team' => $memberA->name,
                    'away_team' => $memberB->name,
                    'home_score' => 0,
                    'away_score' => 0,
                    'venue' => null,
                    'notes' => 'Auto-generated fixture',
                    'created_at' => now(),
                    'updated_at' => now(),
                ];
            }
        }

        // Insert all fixtures
        QplGame::insert($gamesToCreate);

        return redirect()->route('qpl-games.index')
            ->with('success', 'QBASH Pool League fixtures generated successfully from ' . $startDate . '. You can now edit or delete individual games.');
    }

    /**
     * Show standings table for all members based on QBASH Pool League games.
     */
    public function standings()
    {
        $games = QplGame::all();
        $allMembers = Member::orderBy('name')->get();

        $table = [];
        $membersWhoPlayed = [];

        foreach ($games as $game) {
            $home = $game->home_team;
            $away = $game->away_team;

            // A game is considered "played" if:
            // 1. It's not an auto-generated fixture, OR
            // 2. It has been updated (scores entered), OR
            // 3. It has non-zero scores (even if originally auto-generated)
            $isAutoGenerated = ($game->notes === 'Auto-generated fixture');
            $hasBeenUpdated = ($game->updated_at != $game->created_at);
            $hasScores = ($game->home_score > 0 || $game->away_score > 0);
            
            $isPlayed = !$isAutoGenerated || $hasBeenUpdated || $hasScores;
            
            if ($isPlayed) {
                // Track which members have played (only for actually played games)
                $membersWhoPlayed[$home] = true;
                $membersWhoPlayed[$away] = true;

                // Initialize rows if not present
                if (!isset($table[$home])) {
                    $table[$home] = [
                        'name' => $home,
                        'played' => 0,
                        'won' => 0,
                        'drawn' => 0,
                        'lost' => 0,
                        'goals_for' => 0,
                        'goals_against' => 0,
                        'points' => 0,
                    ];
                }
                if (!isset($table[$away])) {
                    $table[$away] = [
                        'name' => $away,
                        'played' => 0,
                        'won' => 0,
                        'drawn' => 0,
                        'lost' => 0,
                        'goals_for' => 0,
                        'goals_against' => 0,
                        'points' => 0,
                    ];
                }
                // Update played and goals
                $table[$home]['played']++;
                $table[$away]['played']++;

                $table[$home]['goals_for'] += $game->home_score;
                $table[$home]['goals_against'] += $game->away_score;

                $table[$away]['goals_for'] += $game->away_score;
                $table[$away]['goals_against'] += $game->home_score;

                // Determine result (points = number of wins, 1 point per win)
                if ($game->home_score > $game->away_score) {
                    $table[$home]['won']++;
                    $table[$home]['points'] += 1; // 1 point per win
                    $table[$away]['lost']++;
                } elseif ($game->home_score < $game->away_score) {
                    $table[$away]['won']++;
                    $table[$away]['points'] += 1; // 1 point per win
                    $table[$home]['lost']++;
                } else {
                    // draw - no points
                    $table[$home]['drawn']++;
                    $table[$away]['drawn']++;
                    // No points for draws
                }
            }
        }

        // Build standings for members who have played
        $playedStandings = collect($table)->map(function ($row) {
            $row['goal_diff'] = $row['goals_for'] - $row['goals_against'];
            return $row;
        })->sortByDesc('points')
          ->sortByDesc('goal_diff')
          ->sortByDesc('goals_for')
          ->values();

        // Build list of members who haven't played
        $notPlayed = $allMembers->filter(function ($member) use ($membersWhoPlayed) {
            return !isset($membersWhoPlayed[$member->name]);
        })->map(function ($member) {
            return [
                'name' => $member->name,
                'played' => 0,
                'won' => 0,
                'drawn' => 0,
                'lost' => 0,
                'goals_for' => 0,
                'goals_against' => 0,
                'goal_diff' => 0,
                'points' => 0,
            ];
        })->sortBy('name')->values();

        // Get recently played games (not auto-generated, ordered by most recently updated)
        // A game is played if: not auto-generated OR has been updated OR has scores
        $recentGames = QplGame::where(function($query) {
                $query->where(function($q) {
                    $q->where('notes', '!=', 'Auto-generated fixture')
                      ->orWhereNull('notes');
                })
                ->orWhereColumn('updated_at', '!=', 'created_at')
                ->orWhere(function($q) {
                    $q->where('home_score', '>', 0)
                      ->orWhere('away_score', '>', 0);
                });
            })
            ->orderBy('updated_at', 'desc')
            ->orderBy('game_date', 'desc')
            ->limit(10)
            ->get();

        // Get all played games with details for member game history
        $allPlayedGames = QplGame::all()->filter(function($game) {
            $isAutoGenerated = ($game->notes === 'Auto-generated fixture');
            $hasBeenUpdated = ($game->updated_at != $game->created_at);
            $hasScores = ($game->home_score > 0 || $game->away_score > 0);
            return !$isAutoGenerated || $hasBeenUpdated || $hasScores;
        })->sortByDesc('game_date')->sortByDesc('updated_at');

        // Build game history for each member who has played
        $memberGameHistory = [];
        foreach ($allPlayedGames as $game) {
            $home = $game->home_team;
            $away = $game->away_team;
            
            if (!isset($memberGameHistory[$home])) {
                $memberGameHistory[$home] = [];
            }
            if (!isset($memberGameHistory[$away])) {
                $memberGameHistory[$away] = [];
            }
            
            // Add game for home team
            $memberGameHistory[$home][] = [
                'opponent' => $away,
                'score_for' => $game->home_score,
                'score_against' => $game->away_score,
                'result' => $game->home_score > $game->away_score ? 'W' : ($game->home_score < $game->away_score ? 'L' : 'D'),
                'date' => $game->game_date,
                'venue' => $game->venue,
            ];
            
            // Add game for away team
            $memberGameHistory[$away][] = [
                'opponent' => $home,
                'score_for' => $game->away_score,
                'score_against' => $game->home_score,
                'result' => $game->away_score > $game->home_score ? 'W' : ($game->away_score < $game->home_score ? 'L' : 'D'),
                'date' => $game->game_date,
                'venue' => $game->venue,
            ];
        }

        return view('qpl-games.standings', compact('playedStandings', 'notPlayed', 'recentGames', 'memberGameHistory'));
    }

    /**
     * Show the form for creating a new QBASH Pool League game.
     */
    public function create()
    {
        $members = Member::orderBy('name')->get();

        return view('qpl-games.create', compact('members'));
    }

    /**
     * Store a newly created QPL game.
     */
    public function store(Request $request)
    {
        $validated = $request->validate([
            'game_date' => 'required|date',
            'home_team' => 'required|string|max:255',
            'away_team' => 'required|string|max:255',
            'home_score' => 'required|integer|min:0',
            'away_score' => 'required|integer|min:0',
            'venue' => 'nullable|string|max:255',
            'notes' => 'nullable|string',
        ]);

        QplGame::create($validated);

        return redirect()->route('qpl-games.index')
            ->with('success', 'QBASH Pool League game recorded successfully!');
    }

    /**
     * Display the specified QBASH Pool League game.
     */
    public function show(QplGame $qplGame)
    {
        return view('qpl-games.show', compact('qplGame'));
    }

    /**
     * Show the form for editing the specified QBASH Pool League game.
     */
    public function edit(QplGame $qplGame)
    {
        $members = Member::orderBy('name')->get();

        return view('qpl-games.edit', compact('qplGame', 'members'));
    }

    /**
     * Update the specified QPL game.
     */
    public function update(Request $request, QplGame $qplGame)
    {
        $validated = $request->validate([
            'game_date' => 'required|date',
            'home_team' => 'required|string|max:255',
            'away_team' => 'required|string|max:255',
            'home_score' => 'required|integer|min:0',
            'away_score' => 'required|integer|min:0',
            'venue' => 'nullable|string|max:255',
            'notes' => 'nullable|string',
        ]);

        $qplGame->update($validated);

        return redirect()->route('qpl-games.index')
            ->with('success', 'QBASH Pool League game updated successfully!');
    }

    /**
     * Remove the specified QPL game.
     */
    public function destroy(QplGame $qplGame)
    {
        $qplGame->delete();

        return redirect()->route('qpl-games.index')
            ->with('success', 'QBASH Pool League game deleted successfully!');
    }

    /**
     * Delete all auto-generated fixtures (games with 'Auto-generated fixture' note).
     */
    public function deleteGenerated()
    {
        QplGame::where('notes', 'Auto-generated fixture')->delete();

        return redirect()->route('qpl-games.index')
            ->with('success', 'All auto-generated QBASH Pool League fixtures have been deleted.');
    }
}
